# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\registration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1301, 543)
        self.treeView = QtWidgets.QTreeView(Dialog)
        self.treeView.setGeometry(QtCore.QRect(10, 60, 281, 171))
        self.treeView.setObjectName("treeView")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 10, 491, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(800, 10, 491, 401))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(10, 510, 281, 21))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.clear = QtWidgets.QPushButton(Dialog)
        self.clear.setGeometry(QtCore.QRect(1040, 420, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setGeometry(QtCore.QRect(300, 420, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.addPickedID = QtWidgets.QPushButton(Dialog)
        self.addPickedID.setGeometry(QtCore.QRect(920, 420, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.addPickedID.setFont(font)
        self.addPickedID.setObjectName("addPickedID")
        self.load = QtWidgets.QPushButton(Dialog)
        self.load.setGeometry(QtCore.QRect(420, 420, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.load.setFont(font)
        self.load.setObjectName("load")
        self.addPickedID_2 = QtWidgets.QPushButton(Dialog)
        self.addPickedID_2.setGeometry(QtCore.QRect(10, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.addPickedID_2.setFont(font)
        self.addPickedID_2.setObjectName("addPickedID_2")
        self.btnTestMerged = QtWidgets.QPushButton(Dialog)
        self.btnTestMerged.setEnabled(False)
        self.btnTestMerged.setGeometry(QtCore.QRect(540, 420, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.btnTestMerged.setFont(font)
        self.btnTestMerged.setAutoDefault(True)
        self.btnTestMerged.setDefault(False)
        self.btnTestMerged.setObjectName("btnTestMerged")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 240, 281, 171))
        self.listView.setObjectName("listView")
        self.selectPoints = QtWidgets.QPushButton(Dialog)
        self.selectPoints.setGeometry(QtCore.QRect(800, 420, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.selectPoints.setFont(font)
        self.selectPoints.setCheckable(True)
        self.selectPoints.setObjectName("selectPoints")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 420, 281, 81))
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.close = QtWidgets.QPushButton(Dialog)
        self.close.setGeometry(QtCore.QRect(1160, 420, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.close.setFont(font)
        self.close.setObjectName("close")
        self.btn_Previous = QtWidgets.QPushButton(Dialog)
        self.btn_Previous.setGeometry(QtCore.QRect(660, 440, 51, 41))
        self.btn_Previous.setObjectName("btn_Previous")
        self.btn_Post = QtWidgets.QPushButton(Dialog)
        self.btn_Post.setGeometry(QtCore.QRect(730, 440, 51, 41))
        self.btn_Post.setObjectName("btn_Post")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.clear.setText(_translate("Dialog", "Clear All"))
        self.save.setText(_translate("Dialog", "Save"))
        self.addPickedID.setText(_translate("Dialog", "Calc RT\n"
" and Merge"))
        self.load.setText(_translate("Dialog", "Load"))
        self.addPickedID_2.setText(_translate("Dialog", "Open Folder"))
        self.btnTestMerged.setText(_translate("Dialog", "Parameter\n"
"Test Merge"))
        self.selectPoints.setText(_translate("Dialog", "Select\n"
"Points"))
        self.close.setText(_translate("Dialog", "Close"))
        self.btn_Previous.setText(_translate("Dialog", "<"))
        self.btn_Post.setText(_translate("Dialog", ">"))
